spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath*:**/xml/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true

logging:
  level:
    com.chz.mapper: debug